# Generated by Django 3.1 on 2020-08-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easeapp', '0002_auto_20200819_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easeapp.publication'),
        ),
    ]
